language: perl
perl:
  - "5.8.9"
  - "5.10.1"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
sudo: false
services:
  - mysql
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpanm --notest --installdeps .
  - cpanm --notest DBD::Pg DBD::mysql
before_script:
  - mysql -e 'create database interchange_test;'
script:
  - perl Makefile.PL force=1 PREFIX=/home/travis/interchange
  - make
  - perl test.pl
  - make install
  - mkdir /home/travis/catalogs
  - cp -r /home/travis/interchange/strap /home/travis/catalogs/
  - mkdir /home/travis/catalogs/strap/logs
  - cp -fv t/interchange-test/variable.txt /home/travis/catalogs/strap/products/
  - cp -fv t/interchange-test/interchange.cfg /home/travis/interchange/
  - cd /home/travis/interchange
  - ./bin/restart
